name: Create Release
on:
  push:
    branches: [deploy]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  # pull_request:
  #   branches: [deploy]
  #   tags:
  #     - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.RELEASE_DATE }}
          release_name: v${{ env.RELEASE_DATE }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false