# name: Deploy Out Directory to pages

# on:
#   push:
#     branches:
#       - main  # Adjust this to the branch where your out directory is updated

# jobs:
#   deploy:
#     name: Deploy Out Directory
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Install dependencies and build the project using yarn
#       - name: Install dependencies and build
#         run: |
#           yarn install --frozen-lockfile
#           yarn build
#         working-directory: ${{ github.workspace }}
      
#       # Copy the contents of the out directory to a temporary directory
#       - name: Copy out directory
#         run: |
#           mkdir temp_out
#           cp -r out/. temp_out
#         working-directory: ${{ github.workspace }}
      
#       # Create and checkout the pages branch
#       - name: Create and checkout pages branch
#         run: |
#           git checkout -b pages
#           git push -u origin pages
#         continue-on-error: true  # Ignore if the branch already exists
      
#       # Remove existing files in the pages branch (optional)
#       - name: Clean pages branch
#         run: git rm -r .
#         working-directory: ${{ github.workspace }}
#         continue-on-error: true  # Ignore if there are no files to remove
      
#       # Copy the contents of the temporary out directory to the pages branch
#       - name: Copy out to pages branch
#         run: cp -r temp_out/. .
#         working-directory: ${{ github.workspace }}
      
#       # Add, commit, and push changes to the pages branch
#       - name: Commit and push changes
#         run: |
#           git add .
#           git commit -m "Deploy out directory to pages"
#           git push origin pages
#         working-directory: ${{ github.workspace }}
